# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param synth.incrementalSynthesisCache D:/Documents/vivado/vgatest/.Xil/Vivado-26504-DESKTOP-6IOG41U/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Documents/vivado/vgatest/vgatest.cache/wt [current_project]
set_property parent.project_path D:/Documents/vivado/vgatest/vgatest.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Documents/vivado/vgatest/vgatest.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Documents/vivado/vgatest/vgatest.srcs/test7.coe
read_verilog -library xil_defaultlib {
  D:/Documents/vivado/vgatest/vgatest.srcs/source/clk_div.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/clk_gen.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/cmd_parse.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/debounce.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/debouncer.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/lb_ctl.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/meta_harden.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/reset_bridge.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/resp_gen.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/rst_gen.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/seg7decimal.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/to_bcd.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/top_flyinglogo.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/uart_baud_gen.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/uart_rx.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/uart_rx_ctl.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/uart_tx.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/uart_tx_ctl.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/vga_timing.v
  D:/Documents/vivado/vgatest/vgatest.srcs/source/bt_uart.v
}
read_ip -quiet D:/Documents/vivado/vgatest/vgatest.srcs/sources_1/ip/logo_rom/logo_rom.xci
set_property used_in_implementation false [get_files -all d:/Documents/vivado/vgatest/vgatest.srcs/sources_1/ip/logo_rom/logo_rom_ooc.xdc]

read_ip -quiet D:/Documents/vivado/vgatest/vgatest.srcs/sources_1/ip/clk_core/clk_core.xci
set_property used_in_implementation false [get_files -all d:/Documents/vivado/vgatest/vgatest.srcs/sources_1/ip/clk_core/clk_core_board.xdc]
set_property used_in_implementation false [get_files -all d:/Documents/vivado/vgatest/vgatest.srcs/sources_1/ip/clk_core/clk_core.xdc]
set_property used_in_implementation false [get_files -all d:/Documents/vivado/vgatest/vgatest.srcs/sources_1/ip/clk_core/clk_core_ooc.xdc]

read_ip -quiet D:/Documents/vivado/vgatest/vgatest.srcs/sources_1/ip/char_fifo/char_fifo.xci
set_property used_in_implementation false [get_files -all d:/Documents/vivado/vgatest/vgatest.srcs/sources_1/ip/char_fifo/char_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/Documents/vivado/vgatest/vgatest.srcs/sources_1/ip/char_fifo/char_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Documents/vivado/vgatest/vgatest.srcs/sources_1/ip/char_fifo/char_fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Documents/vivado/vgatest/vgatest.srcs/constrs_1/new/display_vga.xdc
set_property used_in_implementation false [get_files D:/Documents/vivado/vgatest/vgatest.srcs/constrs_1/new/display_vga.xdc]

read_xdc D:/Documents/vivado/vgatest/vgatest.srcs/constraints/bluetooth.xdc
set_property used_in_implementation false [get_files D:/Documents/vivado/vgatest/vgatest.srcs/constraints/bluetooth.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top bt_uart -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bt_uart.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bt_uart_utilization_synth.rpt -pb bt_uart_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
