# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/myproject/n338/BitExample/BitExample.cache/wt [current_project]
set_property parent.project_path D:/myproject/n338/BitExample/BitExample.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/myproject/n338/BitExample/BitExample.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/myproject/n338/BitExample/BitExample.srcs/sources_1/imports/new/beep.v
  D:/myproject/n338/BitExample/BitExample.srcs/sources_1/imports/new/seg7decimal.v
  D:/myproject/n338/BitExample/BitExample.srcs/sources_1/imports/new/vga_char.v
  D:/myproject/n338/BitExample/BitExample.srcs/sources_1/new/BitExample.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/myproject/n338/BitExample/BitExample.srcs/constrs_1/imports/new/BitEE338.xdc
set_property used_in_implementation false [get_files D:/myproject/n338/BitExample/BitExample.srcs/constrs_1/imports/new/BitEE338.xdc]


synth_design -top BitExample -part xc7a35tcsg324-2


write_checkpoint -force -noxdef BitExample.dcp

catch { report_utilization -file BitExample_utilization_synth.rpt -pb BitExample_utilization_synth.pb }
