# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param synth.incrementalSynthesisCache C:/Users/everything411/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-6436-DESKTOP-6IOG41U/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.cache/wt [current_project]
set_property parent.project_path D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Documents/vivado/CPU_Pipeline/MIPS/test_pipeline.coe
add_files D:/Documents/vivado/CPU_Pipeline/MIPS/test_pipeline2.coe
add_files D:/Documents/vivado/CPU_Pipeline/MIPS/fibonacci.coe
add_files d:/Documents/vivado/CPU_Pipeline/MIPS/mips02text.dmp.coe
read_verilog D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/new/predef.vh
read_verilog -library xil_defaultlib {
  D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/new/control.v
  D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/new/ex.v
  D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/new/ex_mem.v
  D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/new/id.v
  D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/new/id_ex.v
  D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/new/if_id.v
  D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/new/mem.v
  D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/new/mem_wb.v
  D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/new/pc.v
  D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/new/regfile.v
  D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/new/seg7decimal.v
  D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/new/timer_gen.v
  D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/new/cpu_pipeline.v
}
read_ip -quiet D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/ip/inst_rom/inst_rom.xci
set_property used_in_implementation false [get_files -all d:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/ip/inst_rom/inst_rom_ooc.xdc]

read_ip -quiet D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/ip/data_ram/data_ram.xci
set_property used_in_implementation false [get_files -all d:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/sources_1/ip/data_ram/data_ram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/constrs_1/CPU_Pipeline.xdc
set_property used_in_implementation false [get_files D:/Documents/vivado/CPU_Pipeline/CPU_Pipeline.srcs/constrs_1/CPU_Pipeline.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cpu_pipeline -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cpu_pipeline.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cpu_pipeline_utilization_synth.rpt -pb cpu_pipeline_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
